apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-run
  labels: 
    app: sysbench-run
spec:
  parallelism: 3
  template:
    metadata:
      labels:
        app: sysbench-run
    spec:
      restartPolicy: Never
      containers:
      - name: sysbench
        image: uhub.ucloud.cn/pingcap/sysbench:latest
        env:
        - name: TABLE_COUNT
          value: "16"
        - name: TABLE_SIZE
          value: "10000000"
        - name: TEST_NAME
          value: "oltp_point_select"
        - name: TIDB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['tidb-host']
        command:
        - sysbench
        - --config-file=/etc/sysbench/bench.conf
        - --mysql-host=$(TIDB_HOST)
        - $(TEST_NAME)
        - --tables=$(TABLE_COUNT)
        - --table-size=$(TABLE_SIZE)
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/sysbench
      volumes:
      - name: config
        configMap:
          name: sysbench-config
          items:
          - key: bench-config
            path: bench.conf
