apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-warmup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sysbench-warmup
        image: uhub.ucloud.cn/pingcap/sysbench:latest
        env:
        - name: TABLE_COUNT
          value: "16"
        - name: TABLE_SIZE
          value: "10000000"
        - name: TEST_NAME
          value: "oltp_common"
        - name: TIDB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['tidb-host']
        command:
        - sysbench
        - --config-file=/etc/sysbench/warmup.conf
        - --mysql-host=$(TIDB_HOST)
        - $(TEST_NAME)
        - --tables=$(TABLE_COUNT)
        - --table-size=$(TABLE_SIZE)
        - prewarm  
        volumeMounts:
        - name: config
          mountPath: /etc/sysbench
      volumes:
      - name: config
        configMap:
          name: sysbench-config
          items:
          - key: warmup-config
            path: warmup.conf
