name: verify

on:
  pull_request:
    branches:
    - master
    - release-*

jobs:

  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Basic checks
      run: make check-setup check
    - name: Build binaries and images
      run: make docker e2e-docker cli
    - name: Unit Tests
      run: make test
